### ISSUE TITLE
Can't start up

### ISSUE THREAD

**Issue by Haroenv** [socketsupply/union-app-studio#8]
```
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.<anonymous> (/private/var/folders/6k/6s3j_ths2s715kn3v1_0yfz00000gp/T/AppTranslocation/A7E7536B-7FB6-4313-9BF1-00967BABD12D/d/Scratches.app/Contents/Resources/app.asar/index.js:20:18)
    at Object.<anonymous> (/private/var/folders/6k/6s3j_ths2s715kn3v1_0yfz00000gp/T/AppTranslocation/A7E7536B-7FB6-4313-9BF1-00967BABD12D/d/Scratches.app/Contents/Resources/app.asar/index.js:70:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/private/var/folders/6k/6s3j_ths2s715kn3v1_0yfz00000gp/T/AppTranslocation/A7E7536B-7FB6-4313-9BF1-00967BABD12D/d/Scratches.app/Contents/Resources/electron.asar/browser/init.js:171:8)
```

This is from the latest release on GitHub (0.0.4)

<img width="420" alt="screen shot 2018-01-22 at 09 40 14" src="https://user-images.githubusercontent.com/6270048/35211855-6b5d109a-ff58-11e7-97fc-83f9934bc987.png">

<img width="420" alt="screen shot 2018-01-22 at 09 40 55" src="https://user-images.githubusercontent.com/6270048/35211863-7778975a-ff58-11e7-8c60-4ab8b6cf1a9c.png">

(slightly different error message opened twice)

**Comment by heapwolf** [comment]
Agh, thank you! This should be fixed in the latest release - https://github.com/0x00A/scratches/releases/tag/0.0.5

**Comment by Haroenv** [comment]
Yep, starts up now 🙌
